### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by rexdivakar** [m-amaresh/amfi-nav-api#1]
Hi @m-amaresh Is this project still in active status? If so I would like to colaborate with you on integrating API's

**Comment by m-amaresh** [comment]
Hi @rexdivakar , Thanks for reaching out. Due to some personal commitments I have not worked in this for long, But happy to restart and collaborate. Let me know what you have in mind

**Comment by rexdivakar** [comment]
Hey @m-amaresh I have a hobby project which scrapes NSE data over batch load and i have built API's sending data over rapidapi and i would like to work with you in expanding the work improving existing services together and build a dashboard kind of reporting tool with more detailed insights.

https://rapidapi.com/rexzki2s1l/api/nse-market2

let me know if you are available over telegram or discord so we can have a quick talk?

**Comment by m-amaresh** [comment]
I am reachable at @amaresh23k in Telegram
